import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import aiLogo from '../assets/ai_logo.jpg';

let cachedLogoDataUrl = null;

export const getLogoDataUrl = () => {
  if (cachedLogoDataUrl) return Promise.resolve(cachedLogoDataUrl);
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = img.naturalWidth || img.width;
        canvas.height = img.naturalHeight || img.height;
        const ctx = canvas.getContext('2d');
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        ctx.drawImage(img, 0, 0);
        cachedLogoDataUrl = canvas.toDataURL('image/jpeg', 0.95);
        resolve(cachedLogoDataUrl);
      } catch (e) {
        resolve(aiLogo);
      }
    };
    img.onerror = () => resolve(aiLogo);
    img.src = aiLogo;
  });
};

export const applyPDFHeader = (doc, { title, metaInfo, logoDataUrl }) => {
  const pageWidth = doc.internal.pageSize.width;
  const centerX = pageWidth / 2;

  // Add Logo at Top Left Side (x=14, y=8, w=28, h=16)
  if (logoDataUrl) {
    try {
      doc.addImage(logoDataUrl, 'JPEG', 14, 8, 28, 16);
    } catch (e) {
      console.warn('PDF Logo render warning:', e);
    }
  }

  // Centered Header Text
  doc.setFontSize(13.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('ASEMS - AARYA SITE EXPENSE MANAGEMENT SYSTEM', centerX, 14, { align: 'center' });

  doc.setFontSize(10.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(37, 99, 235); // Royal Blue
  doc.text(title, centerX, 21, { align: 'center' });

  if (metaInfo) {
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(metaInfo, centerX, 27, { align: 'center' });
  }

  // Subtle Header Divider Line
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.4);
  doc.line(14, 31, pageWidth - 14, 31);
};

export const applyPDFFooter = (doc) => {
  const totalPages = doc.internal.getNumberOfPages ? doc.internal.getNumberOfPages() : 1;
  const pageWidth = doc.internal.pageSize.getWidth ? doc.internal.pageSize.getWidth() : doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.getHeight ? doc.internal.pageSize.getHeight() : doc.internal.pageSize.height;

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    // Signature Lines at Bottom
    doc.setDrawColor(148, 163, 184); // #94a3b8
    doc.setLineWidth(0.35);

    // Left signature: System Administrator
    const leftSigWidth = 55;
    doc.line(14, pageHeight - 24, 14 + leftSigWidth, pageHeight - 24);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text('System Administrator', 14 + (leftSigWidth / 2), pageHeight - 20, { align: 'center' });

    // Right signature: Authorized Signatory
    const rightSigWidth = 55;
    doc.line(pageWidth - 14 - rightSigWidth, pageHeight - 24, pageWidth - 14, pageHeight - 24);
    doc.text('Authorized Signatory', pageWidth - 14 - (rightSigWidth / 2), pageHeight - 20, { align: 'center' });

    // Bottom Divider Line
    doc.setDrawColor(203, 213, 225); // #cbd5e1
    doc.setLineWidth(0.4);
    doc.line(14, pageHeight - 14, pageWidth - 14, pageHeight - 14);

    // Company CIN, Phone, Website & Address on Bottom-Left
    doc.setFontSize(6.8);
    doc.setTextColor(100, 116, 139);
    doc.text('AARYA INNOVTECH PVT. LTD. CIN: U29305MH2019PTC327551 | +91 9359604384 | https://aaryainnovtech.com/', 14, pageHeight - 9.5);
    doc.text('Nashik Office: Flat No.4A, Sayali Darshan A-Wing, Makhamalabad Road, Nashik-422003.', 14, pageHeight - 5.5);

    // Page Number and System Generated on Bottom-Right
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 14, pageHeight - 9.5, { align: 'right' });
    doc.text('Generated by System', pageWidth - 14, pageHeight - 5.5, { align: 'right' });
  }
};

export const exportToPDF = async (title, columns, rows, metaInfo = '') => {
  try {
    const doc = new jsPDF();
    const logoDataUrl = await getLogoDataUrl();
    
    applyPDFHeader(doc, {
      title,
      metaInfo: metaInfo || `Generated on: ${new Date().toLocaleString()}`,
      logoDataUrl
    });

    const safeRows = rows.map(row => row.map(cell => cell ? cell.toString() : '-'));

    if (typeof autoTable === 'function') {
      autoTable(doc, {
        head: [columns],
        body: safeRows,
        startY: 35,
        margin: { bottom: 30 },
        styles: { fontSize: 8.5 },
        headStyles: { fillColor: [59, 130, 246] }
      });
    } else if (typeof doc.autoTable === 'function') {
      doc.autoTable({
        head: [columns],
        body: safeRows,
        startY: 35,
        margin: { bottom: 30 },
        styles: { fontSize: 8.5 },
        headStyles: { fillColor: [59, 130, 246] }
      });
    } else {
      alert("PDF library is not fully loaded. Please wait a second and try again.");
      return;
    }

    applyPDFFooter(doc);
    doc.save(`${title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
  } catch (error) {
    console.error("PDF Generation Error: ", error);
    alert("Error generating PDF: " + error.message);
  }
};

export const exportToExcel = (title, columns, rows) => {
  try {
    // Basic CSV format
    const safeRows = rows.map(row => 
      row.map(cell => `"${(cell ? cell.toString() : '-').replace(/"/g, '""')}"`).join(',')
    );
    const csvContent = [columns.join(','), ...safeRows].join('\n');
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    
    link.setAttribute("href", url);
    link.setAttribute("download", `${title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  } catch (error) {
    console.error("Excel Generation Error: ", error);
    alert("Error generating Excel file: " + error.message);
  }
};

export const handlePrint = () => {
  window.print();
};

