import React from 'react';

const PrintFooter = () => {
  return (
    <div className="print-only" style={{ display: 'none', marginTop: '2.5rem', pageBreakInside: 'avoid' }}>
      {/* Signatures Row */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: '1.25rem', padding: '0 0.5rem' }}>
        <div style={{ textAlign: 'center', width: '220px' }}>
          <div style={{ borderBottom: '1px solid #94a3b8', marginBottom: '0.4rem', height: '1px' }}></div>
          <span style={{ fontSize: '8.5pt', color: '#475569', fontWeight: '600' }}>System Administrator</span>
        </div>

        <div style={{ textAlign: 'center', width: '220px' }}>
          <div style={{ borderBottom: '1px solid #94a3b8', marginBottom: '0.4rem', height: '1px' }}></div>
          <span style={{ fontSize: '8.5pt', color: '#475569', fontWeight: '600' }}>Authorized Signatory</span>
        </div>
      </div>

      {/* Footer Details Bar */}
      <div style={{ borderTop: '1px solid #cbd5e1', paddingTop: '0.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', fontSize: '7pt', color: '#64748b' }}>
        <div>
          <div style={{ fontWeight: '600', color: '#334155' }}>
            AARYA INNOVTECH PVT. LTD. CIN: U29305MH2019PTC327551 | +91 9359604384 | https://aaryainnovtech.com/
          </div>
          <div style={{ marginTop: '2px' }}>
            Nashik Office: Flat No.4A, Sayali Darshan A-Wing, Makhamalabad Road, Nashik-422003.
          </div>
        </div>
        <div style={{ textAlign: 'right', whiteSpace: 'nowrap' }}>
          <div>Page 1 of 1</div>
          <div style={{ marginTop: '2px' }}>Generated by System</div>
        </div>
      </div>
    </div>
  );
};

export default PrintFooter;
